# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Software/ZAllProject/vivadoproject/Exp6/code/constraint.xdc

# IP: ip/multiplier/multiplier.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==multiplier || ORIG_REF_NAME==multiplier} -quiet] -quiet
